<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CompanyAsset;
use App\Models\AssetActivityLog;
use App\Models\AssetMaintenanceRecord;
use App\Models\AssetFinancialRecord;
use App\Models\AssetNote;
use App\Models\AssetDocument;
use App\Models\AssetSetting;
use Carbon\Carbon;
use Illuminate\Support\Facades\Schema;

class CompanyAssetSeeder extends Seeder
{
    public function run(): void
    {
        if (Schema::hasTable('asset_documents')) AssetDocument::truncate();
        if (Schema::hasTable('asset_notes')) AssetNote::truncate();
        if (Schema::hasTable('asset_financial_records')) AssetFinancialRecord::truncate();
        if (Schema::hasTable('asset_maintenance_records')) AssetMaintenanceRecord::truncate();
        if (Schema::hasTable('asset_activity_logs')) AssetActivityLog::truncate();
        if (Schema::hasTable('company_assets')) CompanyAsset::truncate();
        if (Schema::hasTable('asset_settings')) AssetSetting::truncate();

        $defaultDocs = [
            [
                'name' => 'User_Manual.pdf',
                'size' => '2.4 MB',
                'type' => 'PDF',
                'url' => '/documents/User_Manual.pdf',
            ],
            [
                'name' => 'Purchase_Invoice.xlsx',
                'size' => '128 KB',
                'type' => 'XLSX',
                'url' => '/documents/Purchase_Invoice.xlsx',
            ],
            [
                'name' => 'Warranty_Details.docx',
                'size' => '320 KB',
                'type' => 'DOC',
                'url' => '/documents/Warranty_Details.docx',
            ],
        ];

        $assets = [
            // Page 1 primary 8 assets shown in mockup
            [
                'asset_tag' => 'ASSET-001',
                'name' => 'Tajima Embroidery Machine',
                'category' => 'Embroidery Machines',
                'brand' => 'Tajima',
                'model' => 'TMAR-K1506C',
                'serial_number' => 'TJ123456789',
                'purchase_date' => '2023-01-12',
                'condition' => 'New',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Tajima Industries Ltd.',
                'location' => 'Brooklyn, NY',
                'department' => 'Production',
                'assigned_to' => 'Production Team',
                'purchase_cost' => 15500.00,
                'invoice_number' => 'INV-2023-001',
                'invoice_date' => '2023-01-12',
                'vendor_name_address' => 'ABC Equipment Co. | 123 Industrial Blvd, Brooklyn, NY 11207',
                'warranty_status' => 'Active',
                'warranty_provider' => 'Tajima USA',
                'warranty_start_date' => '2023-01-12',
                'warranty_expiration_date' => '2026-01-12',
                'warranty_reference_number' => 'WRT-2023-001',
                'description' => 'High-performance multi-needle embroidery machine used for commercial embroidery production.',
                'images' => [
                    '/images/assets/tajima_embroidery.png',
                    '/images/assets/modal_tajima_1.png',
                    '/images/assets/modal_tajima_2.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => true,
                'service_type' => 'Routine Check',
                'service_frequency' => 'Every 3 Months',
                'next_service_date' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'notes' => 'Primary commercial embroidery station for multi-head jobs.',
            ],
            [
                'asset_tag' => 'ASSET-002',
                'name' => 'Dell Workstation',
                'category' => 'Computers & IT',
                'brand' => 'Dell',
                'model' => 'OptiPlex 7000',
                'serial_number' => 'DL987654321',
                'purchase_date' => '2023-02-20',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Dell Technologies',
                'location' => 'Forest Park, GA',
                'department' => 'IT & Design',
                'assigned_to' => 'Design Team',
                'purchase_cost' => 1850.00,
                'invoice_number' => 'INV-2023-014',
                'invoice_date' => '2023-02-20',
                'vendor_name_address' => 'Dell Commercial Direct | Round Rock, TX',
                'warranty_status' => 'Active',
                'warranty_provider' => 'Dell ProSupport',
                'warranty_start_date' => '2023-02-20',
                'warranty_expiration_date' => '2026-02-20',
                'warranty_reference_number' => 'WRT-DELL-7000',
                'description' => 'High-speed digitizing and graphic rendering workstation for Wilcom embroidery digitizing.',
                'images' => [
                    '/images/assets/dell_workstation.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => false,
                'notes' => 'Dedicated to embroidery digitizing and vector graphics.',
            ],
            [
                'asset_tag' => 'ASSET-003',
                'name' => 'Wilcom Digitizing Terminal',
                'category' => 'Computers & IT',
                'brand' => 'Dell',
                'model' => 'Precision 3660',
                'serial_number' => 'DL12398745',
                'purchase_date' => '2023-03-01',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Dell Technologies',
                'location' => 'Brooklyn, NY',
                'department' => 'Design',
                'assigned_to' => 'Lead Digitizer',
                'purchase_cost' => 2100.00,
                'invoice_number' => 'INV-2023-019',
                'invoice_date' => '2023-03-01',
                'vendor_name_address' => 'Dell Commercial Direct | Round Rock, TX',
                'warranty_status' => 'Active',
                'warranty_provider' => 'Dell ProSupport',
                'warranty_start_date' => '2023-03-01',
                'warranty_expiration_date' => '2026-03-01',
                'warranty_reference_number' => 'WRT-DELL-3660',
                'description' => 'Dedicated digitizing terminal with high DPI dual monitors and Wilcom EmbroideryStudio E4.5.',
                'images' => [
                    '/images/assets/dell_workstation.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => false,
                'notes' => 'Wilcom dongle key attached to rear USB port.',
            ],
            [
                'asset_tag' => 'ASSET-004',
                'name' => 'Office Printer',
                'category' => 'Office Equipment',
                'brand' => 'HP',
                'model' => 'LaserJet Pro M404',
                'serial_number' => 'HP58433221',
                'purchase_date' => '2023-04-05',
                'condition' => 'Good',
                'status' => 'under_maintenance',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'HP Inc.',
                'location' => 'Alpharetta, GA',
                'department' => 'Administration',
                'assigned_to' => 'Office Staff',
                'purchase_cost' => 650.00,
                'invoice_number' => 'INV-2023-088',
                'invoice_date' => '2023-04-05',
                'vendor_name_address' => 'Staples Business Advantage | Alpharetta, GA',
                'warranty_status' => 'Active',
                'warranty_provider' => 'HP Care Pack',
                'warranty_start_date' => '2023-04-05',
                'warranty_expiration_date' => '2025-04-05',
                'warranty_reference_number' => 'HP-CARE-889',
                'description' => 'Workgroup monochrome laser printer for order packing slips and invoices.',
                'images' => [
                    '/images/assets/office_printer.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => true,
                'service_type' => 'Routine Maintenance',
                'service_frequency' => 'Every Month',
                'next_service_date' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'notes' => 'Toner replacement and roller cleaning in progress.',
            ],
            [
                'asset_tag' => 'ASSET-007',
                'name' => 'Air Compressor',
                'category' => 'Other Equipment',
                'brand' => 'Ingersoll Rand',
                'model' => 'SS5L5',
                'serial_number' => 'IR987654321',
                'purchase_date' => '2023-02-01',
                'condition' => 'Fair',
                'status' => 'out_of_service',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Ingersoll Rand',
                'location' => 'McDonough, GA',
                'department' => 'Maintenance',
                'assigned_to' => 'Facilities Team',
                'purchase_cost' => 2200.00,
                'invoice_number' => 'INV-2023-022',
                'invoice_date' => '2023-02-01',
                'vendor_name_address' => 'Grainger Industrial Supply | Atlanta, GA',
                'warranty_status' => 'Expired',
                'warranty_provider' => 'Ingersoll Rand',
                'warranty_start_date' => '2023-02-01',
                'warranty_expiration_date' => '2024-02-01',
                'warranty_reference_number' => 'IR-EXP-555',
                'description' => '5HP 60 gallon single stage air compressor powering pneumatic hooping frames.',
                'images' => [
                    '/images/assets/air_compressor.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => true,
                'service_type' => 'Service Due',
                'service_frequency' => 'Every 3 Months',
                'next_service_date' => Carbon::now()->addDays(8)->format('Y-m-d'),
                'notes' => 'Pressure valve leak detected. Awaiting replacement parts.',
            ],
            [
                'asset_tag' => 'ASSET-005',
                'name' => 'UPS Backup',
                'category' => 'Computers & IT',
                'brand' => 'APC',
                'model' => 'Smart-UPS 1500',
                'serial_number' => 'APC12233445',
                'purchase_date' => '2023-01-18',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Schneider Electric',
                'location' => 'South Fulton, GA',
                'department' => 'IT',
                'assigned_to' => 'IT Infrastructure Team',
                'purchase_cost' => 850.00,
                'invoice_number' => 'INV-2023-009',
                'invoice_date' => '2023-01-18',
                'vendor_name_address' => 'CDW Logistics | Chicago, IL',
                'warranty_status' => 'Active',
                'warranty_provider' => 'APC Schneider',
                'warranty_start_date' => '2023-01-18',
                'warranty_expiration_date' => '2026-01-18',
                'warranty_reference_number' => 'APC-1500-SR',
                'description' => 'Pure sine wave battery backup for network servers and central control workstation.',
                'images' => [
                    '/images/assets/ups_backup.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => false,
                'notes' => 'Battery health 98%, tested monthly.',
            ],
            [
                'asset_tag' => 'ASSET-006',
                'name' => 'Cutting Table',
                'category' => 'Furniture & Fixtures',
                'brand' => 'TFI',
                'model' => 'CT-6010',
                'serial_number' => 'TS66778890',
                'purchase_date' => '2023-03-10',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'TFI Manufacturing',
                'location' => 'Forest Park, GA',
                'department' => 'Production',
                'assigned_to' => 'Production Team',
                'purchase_cost' => 1400.00,
                'invoice_number' => 'INV-2023-045',
                'invoice_date' => '2023-03-10',
                'vendor_name_address' => 'Textile Furnishings Inc | Atlanta, GA',
                'warranty_status' => 'Active',
                'warranty_provider' => 'TFI Standard',
                'warranty_start_date' => '2023-03-10',
                'warranty_expiration_date' => '2028-03-10',
                'warranty_reference_number' => 'TFI-CT6010',
                'description' => 'Heavy duty industrial fabric cutting table with self-healing mat grid.',
                'images' => [
                    '/images/assets/cutting_table.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => false,
                'notes' => 'Surface cleaned and inspected weekly.',
            ],
            [
                'asset_tag' => 'ASSET-008',
                'name' => 'Office Chair',
                'category' => 'Furniture & Fixtures',
                'brand' => 'Herman Miller',
                'model' => 'Aeron',
                'serial_number' => 'HM33465667',
                'purchase_date' => '2023-01-05',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Herman Miller',
                'location' => 'Brooklyn, NY',
                'department' => 'Administration',
                'assigned_to' => 'Management',
                'purchase_cost' => 1195.00,
                'invoice_number' => 'INV-2023-003',
                'invoice_date' => '2023-01-05',
                'vendor_name_address' => 'Design Within Reach | New York, NY',
                'warranty_status' => 'Active',
                'warranty_provider' => 'Herman Miller 12-Year',
                'warranty_start_date' => '2023-01-05',
                'warranty_expiration_date' => '2035-01-05',
                'warranty_reference_number' => 'HM-AERON-33',
                'description' => 'Ergonomic Pellicle mesh task chair for admin office workstation.',
                'images' => [
                    '/images/assets/office_chair.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => false,
                'notes' => 'Excellent ergonomic condition.',
            ],
            [
                'asset_tag' => 'ASSET-010',
                'name' => 'HVAC Unit',
                'category' => 'Other Equipment',
                'brand' => 'Trane',
                'model' => 'XR14',
                'serial_number' => 'TR998877665',
                'purchase_date' => '2023-05-05',
                'condition' => 'Good',
                'status' => 'under_maintenance',
                'purchase_type' => 'Purchased',
                'manufacturer' => 'Trane Inc.',
                'location' => 'Douglasville, GA',
                'department' => 'Facilities',
                'assigned_to' => 'Facilities Team',
                'purchase_cost' => 6800.00,
                'invoice_number' => 'INV-2023-102',
                'invoice_date' => '2023-05-05',
                'vendor_name_address' => 'Trane Commercial HVAC Solutions | Atlanta, GA',
                'warranty_status' => 'Expired',
                'warranty_provider' => 'Trane Standard 1-Year',
                'warranty_start_date' => '2023-05-05',
                'warranty_expiration_date' => '2024-05-05',
                'warranty_reference_number' => 'TR-XR14-88',
                'description' => 'Rooftop climate and humidity control system for embroidery workshop.',
                'images' => [
                    '/images/assets/hvac_unit.png',
                ],
                'documents' => $defaultDocs,
                'has_maintenance_schedule' => true,
                'service_type' => 'Filter Replacement',
                'service_frequency' => 'Every 6 Months',
                'next_service_date' => Carbon::now()->addDays(22)->format('Y-m-d'),
                'notes' => 'Seasonal air filter and coil cleaning scheduled.',
            ],

            // 7 additional Embroidery Machines -> total 8
            [
                'asset_tag' => 'ASSET-011',
                'name' => 'Barudan 6-Head Machine',
                'category' => 'Embroidery Machines',
                'brand' => 'Barudan',
                'model' => 'BEXY-S1506C',
                'serial_number' => 'BD55443322',
                'purchase_date' => '2023-06-15',
                'condition' => 'New',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Production',
                'assigned_to' => 'Production Team',
                'purchase_cost' => 28500.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],
            [
                'asset_tag' => 'ASSET-012',
                'name' => 'Brother Commercial PR1055X',
                'category' => 'Embroidery Machines',
                'brand' => 'Brother',
                'model' => 'PR1055X',
                'serial_number' => 'BR88776655',
                'purchase_date' => '2023-07-20',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Forest Park, GA',
                'department' => 'Production',
                'assigned_to' => 'Cap Embroidery Specialist',
                'purchase_cost' => 12500.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],
            [
                'asset_tag' => 'ASSET-014',
                'name' => 'Melco EMT16X Single Head',
                'category' => 'Embroidery Machines',
                'brand' => 'Melco',
                'model' => 'EMT16X',
                'serial_number' => 'ML11223344',
                'purchase_date' => '2023-08-11',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Production',
                'assigned_to' => 'Sample Department',
                'purchase_cost' => 14200.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],
            [
                'asset_tag' => 'ASSET-015',
                'name' => 'Tajima 8-Head TFMX-IIC',
                'category' => 'Embroidery Machines',
                'brand' => 'Tajima',
                'model' => 'TFMX-IIC1508',
                'serial_number' => 'TJ99001122',
                'purchase_date' => '2023-09-01',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Production',
                'assigned_to' => 'High Volume Team',
                'purchase_cost' => 38000.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],
            [
                'asset_tag' => 'ASSET-016',
                'name' => 'SWF Dual Function 1502D',
                'category' => 'Embroidery Machines',
                'brand' => 'SWF',
                'model' => 'MAN-12',
                'serial_number' => 'SW44556677',
                'purchase_date' => '2023-10-14',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Forest Park, GA',
                'department' => 'Production',
                'assigned_to' => 'Production Team',
                'purchase_cost' => 18900.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],
            [
                'asset_tag' => 'ASSET-017',
                'name' => 'Ricoma 1501-TC Compact',
                'category' => 'Embroidery Machines',
                'brand' => 'Ricoma',
                'model' => '1501-TC',
                'serial_number' => 'RC77889900',
                'purchase_date' => '2023-11-05',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Alpharetta, GA',
                'department' => 'Custom Orders',
                'assigned_to' => 'Custom Team',
                'purchase_cost' => 9800.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],
            [
                'asset_tag' => 'ASSET-018',
                'name' => 'HappyJapan HCD2-1501',
                'category' => 'Embroidery Machines',
                'brand' => 'HappyJapan',
                'model' => 'HCD2-1501',
                'serial_number' => 'HJ33221100',
                'purchase_date' => '2023-12-01',
                'condition' => 'Good',
                'status' => 'under_maintenance',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Production',
                'assigned_to' => 'Production Team',
                'purchase_cost' => 13400.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/tajima_embroidery.png'],
            ],

            // 2 more Computers & IT -> total 5 (ASSET-002, ASSET-003, ASSET-005, ASSET-019, ASSET-020)
            [
                'asset_tag' => 'ASSET-019',
                'name' => 'Apple Mac Studio M2 Max',
                'category' => 'Computers & IT',
                'brand' => 'Apple',
                'model' => 'Mac Studio M2',
                'serial_number' => 'AP99887766',
                'purchase_date' => '2024-01-10',
                'condition' => 'New',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Design',
                'assigned_to' => 'Senior Art Director',
                'purchase_cost' => 2400.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/dell_workstation.png'],
            ],
            [
                'asset_tag' => 'ASSET-020',
                'name' => 'Synology NAS Storage 32TB',
                'category' => 'Computers & IT',
                'brand' => 'Synology',
                'model' => 'DS1821+',
                'serial_number' => 'SY11223344',
                'purchase_date' => '2024-02-15',
                'condition' => 'New',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'IT',
                'assigned_to' => 'Network Admin',
                'purchase_cost' => 2800.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/ups_backup.png'],
            ],

            // 3 more Office Equipment -> total 4 (ASSET-004, ASSET-022, ASSET-023, ASSET-024)
            [
                'asset_tag' => 'ASSET-022',
                'name' => 'Zebra Thermal Barcode Printer',
                'category' => 'Office Equipment',
                'brand' => 'Zebra',
                'model' => 'ZD421',
                'serial_number' => 'ZB33445566',
                'purchase_date' => '2024-01-25',
                'condition' => 'New',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Shipping',
                'assigned_to' => 'Shipping Team',
                'purchase_cost' => 450.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/office_printer.png'],
            ],
            [
                'asset_tag' => 'ASSET-023',
                'name' => 'Fellowes Heavy-Duty Paper Shredder',
                'category' => 'Office Equipment',
                'brand' => 'Fellowes',
                'model' => 'Powershred 99Ci',
                'serial_number' => 'FL77889900',
                'purchase_date' => '2024-02-10',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Alpharetta, GA',
                'department' => 'Administration',
                'assigned_to' => 'Accounting',
                'purchase_cost' => 380.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/office_printer.png'],
            ],
            [
                'asset_tag' => 'ASSET-024',
                'name' => 'Epson SureColor Label Printer',
                'category' => 'Office Equipment',
                'brand' => 'Epson',
                'model' => 'ColorWorks C3500',
                'serial_number' => 'EP44556677',
                'purchase_date' => '2024-03-05',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Packaging',
                'assigned_to' => 'Fulfillment Team',
                'purchase_cost' => 1650.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/office_printer.png'],
            ],

            // 2 more Furniture & Fixtures -> total 4 (ASSET-006, ASSET-008, ASSET-009, ASSET-013)
            [
                'asset_tag' => 'ASSET-009',
                'name' => 'Heavy Duty Steel Thread Rack',
                'category' => 'Furniture & Fixtures',
                'brand' => 'Global Industrial',
                'model' => 'GI-RACK-400',
                'serial_number' => 'GI11223344',
                'purchase_date' => '2024-01-15',
                'condition' => 'Good',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Production',
                'assigned_to' => 'Thread Inventory Specialist',
                'purchase_cost' => 750.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/cutting_table.png'],
            ],
            [
                'asset_tag' => 'ASSET-013',
                'name' => 'Master Maintenance Tool Kit',
                'category' => 'Furniture & Fixtures',
                'brand' => 'DeWalt',
                'model' => 'DWMT75049',
                'serial_number' => 'DW88990011',
                'purchase_date' => '2024-03-12',
                'condition' => 'New',
                'status' => 'in_use',
                'purchase_type' => 'Purchased',
                'location' => 'Forest Park, GA',
                'department' => 'Maintenance',
                'assigned_to' => 'Lead Technician',
                'purchase_cost' => 550.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/cutting_table.png'],
            ],

            // 1 additional Other Equipment with under_maintenance -> makes total 24 (18 in use, 4 under maintenance, 2 out of service)
            [
                'asset_tag' => 'ASSET-025',
                'name' => 'Crown Electric Pallet Jack',
                'category' => 'Other Equipment',
                'brand' => 'Crown',
                'model' => 'WP 3000',
                'serial_number' => 'CR99112233',
                'purchase_date' => '2023-08-20',
                'condition' => 'Good',
                'status' => 'under_maintenance',
                'purchase_type' => 'Purchased',
                'location' => 'Brooklyn, NY',
                'department' => 'Warehouse',
                'assigned_to' => 'Warehouse Lead',
                'purchase_cost' => 4200.00,
                'warranty_status' => 'Active',
                'images' => ['/images/assets/air_compressor.png'],
            ],
        ];

        $createdAssets = [];
        foreach ($assets as $assetData) {
            $createdAssets[$assetData['asset_tag']] = CompanyAsset::create($assetData);
        }

        // Seed Detailed Relations for Primary Asset (ASSET-001 Tajima)
        $tajima = $createdAssets['ASSET-001'] ?? null;
        if ($tajima) {
            // Maintenance Records: Scheduled & History
            AssetMaintenanceRecord::create([
                'asset_id' => $tajima->id,
                'record_type' => 'schedule',
                'maintenance_type' => 'Routine Maintenance',
                'maintenance_title' => 'Quarterly Rotary Hook & Timing Alignment',
                'service_type' => 'Routine Service',
                'description' => 'Quarterly precision lubrication, thread trimmer calibration, and rotary hook check.',
                'status' => 'Scheduled',
                'assigned_to' => 'Tajima Authorized Service',
                'service_provider' => 'Tajima Authorized Service',
                'contact_person' => 'Daniel Sato',
                'phone' => '+1 718 555-0199',
                'email' => 'daniel.sato@tajima-service.com',
                'frequency' => 'Quarterly',
                'start_date' => '2026-03-15',
                'next_service_date' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'provider_type' => 'external',
                'service_date' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'cost' => 450.00,
                'labor_cost' => 350.00,
                'parts_cost' => 100.00,
                'notes' => 'Perform under warranty coverage.',
            ]);

            AssetMaintenanceRecord::create([
                'asset_id' => $tajima->id,
                'record_type' => 'history',
                'maintenance_type' => 'Preventive Maintenance',
                'maintenance_title' => 'Semi-Annual Head Overhaul & Needle Bar Calibration',
                'service_type' => 'Full Service',
                'description' => 'Replaced needle bar reciprocators across heads 1 to 6. Lubricated main drive shafts.',
                'status' => 'Completed',
                'assigned_to' => 'Tajima Authorized Service',
                'service_provider' => 'Tajima Authorized Service',
                'contact_person' => 'Daniel Sato',
                'phone' => '+1 718 555-0199',
                'technician_name' => 'Daniel Sato',
                'invoice_number' => 'INV-TAJ-8890',
                'service_date' => '2025-11-10',
                'completed_at' => Carbon::parse('2025-11-10 16:30:00'),
                'cost' => 620.00,
                'labor_cost' => 400.00,
                'parts_cost' => 220.00,
                'notes' => 'Machine passed all tension calibration tests at 1,000 RPM.',
            ]);

            // Financial Records / Expenses
            AssetFinancialRecord::create([
                'asset_id' => $tajima->id,
                'expense_type' => 'Purchase',
                'description' => 'Initial commercial multi-head embroidery machine purchase.',
                'invoice_number' => 'INV-2023-001',
                'vendor_name' => 'ABC Equipment Co.',
                'amount' => 15500.00,
                'payment_method' => 'Bank Transfer',
                'reference_number' => 'WIRE-2023-0112',
                'is_recurring' => false,
                'expense_date' => '2023-01-12',
            ]);

            AssetFinancialRecord::create([
                'asset_id' => $tajima->id,
                'expense_type' => 'Parts',
                'description' => 'Set of 12 replacement bobbin cases and high-speed rotary hooks.',
                'invoice_number' => 'INV-TAJ-2201',
                'vendor_name' => 'Embroidery Parts Co.',
                'amount' => 380.00,
                'payment_method' => 'Credit Card',
                'reference_number' => 'CC-4921',
                'is_recurring' => false,
                'expense_date' => '2025-06-18',
            ]);

            AssetFinancialRecord::create([
                'asset_id' => $tajima->id,
                'expense_type' => 'Labor',
                'description' => 'Certified technician annual calibration & head synchronization.',
                'invoice_number' => 'INV-SRV-901',
                'vendor_name' => 'Tajima Authorized Service',
                'amount' => 450.00,
                'payment_method' => 'Company Check',
                'reference_number' => 'CHK-10992',
                'is_recurring' => false,
                'expense_date' => '2025-11-10',
            ]);

            // Asset Notes
            AssetNote::create([
                'asset_id' => $tajima->id,
                'author_name' => 'Admin User',
                'author_initials' => 'AD',
                'author_avatar_bg' => 'bg-slate-700',
                'category' => 'General',
                'note_text' => 'Installed new Wilcom high-speed digitizing templates on this machine. Ready for 3D puff embroidery jobs.',
                'created_at' => Carbon::now()->subDays(3),
            ]);

            AssetNote::create([
                'asset_id' => $tajima->id,
                'author_name' => 'Daniel Sato',
                'author_initials' => 'DS',
                'author_avatar_bg' => 'bg-blue-600',
                'category' => 'Maintenance',
                'note_text' => 'Checked needle bar timing on heads 3 and 4. Reset clearances to factory 0.05mm spec. All heads firing smoothly.',
                'created_at' => Carbon::now()->subDays(14),
            ]);

            // Asset Documents
            AssetDocument::create([
                'asset_id' => $tajima->id,
                'title' => 'Purchase Invoice',
                'file_name' => 'invoice_tajima_001.pdf',
                'file_type' => 'pdf',
                'file_size' => '245 KB',
                'category' => 'purchase',
                'document_date' => '2023-01-12',
                'file_url' => '/documents/invoice_tajima_001.pdf',
                'description' => 'Original purchase tax invoice from ABC Equipment Co.',
            ]);

            AssetDocument::create([
                'asset_id' => $tajima->id,
                'title' => 'Warranty Certificate',
                'file_name' => 'warranty_tajima_001.pdf',
                'file_type' => 'pdf',
                'file_size' => '180 KB',
                'category' => 'warranty',
                'document_date' => '2023-01-12',
                'file_url' => '/documents/warranty_tajima_001.pdf',
                'description' => '3-Year manufacturer warranty coverage certificate.',
            ]);

            AssetDocument::create([
                'asset_id' => $tajima->id,
                'title' => 'User Manual',
                'file_name' => 'tajima_manual.pdf',
                'file_type' => 'pdf',
                'file_size' => '12.4 MB',
                'category' => 'manual',
                'document_date' => '2023-01-10',
                'file_url' => '/documents/tajima_manual.pdf',
                'description' => 'Official operation and troubleshooting manual for TMAR-K series.',
            ]);

            AssetDocument::create([
                'asset_id' => $tajima->id,
                'title' => 'Maintenance Records',
                'file_name' => 'maintenance_log.xlsx',
                'file_type' => 'xlsx',
                'file_size' => '320 KB',
                'category' => 'maintenance',
                'document_date' => '2025-03-15',
                'file_url' => '/documents/maintenance_log.xlsx',
                'description' => 'Log sheet for daily, weekly, and monthly oiling & hook cleaning.',
            ]);

            AssetDocument::create([
                'asset_id' => $tajima->id,
                'title' => 'Asset Photo',
                'file_name' => 'asset_photo_001.jpg',
                'file_type' => 'jpg',
                'file_size' => '2.1 MB',
                'category' => 'photo',
                'document_date' => '2023-01-12',
                'file_url' => '/images/assets/tajima_embroidery.png',
                'description' => 'Installation photo at Brooklyn production shop floor.',
            ]);

            AssetDocument::create([
                'asset_id' => $tajima->id,
                'title' => 'Service Report',
                'file_name' => 'service_report.docx',
                'file_type' => 'docx',
                'file_size' => '140 KB',
                'category' => 'maintenance',
                'document_date' => '2025-11-10',
                'file_url' => '/documents/service_report.docx',
                'description' => 'Technician audit report from Tajima Certified Service.',
            ]);
        }

        // Additional Scheduled Maintenance for other assets
        $printerAsset = $createdAssets['ASSET-004'] ?? null;
        if ($printerAsset) {
            AssetMaintenanceRecord::create([
                'asset_id' => $printerAsset->id,
                'record_type' => 'schedule',
                'maintenance_type' => 'Routine Maintenance',
                'maintenance_title' => 'Roller Cleaning & Drum Replacement',
                'service_type' => 'Routine Maintenance',
                'description' => 'Clean paper pickup rollers and install high-yield replacement toner.',
                'status' => 'In Progress',
                'assigned_to' => 'ATL Machine Repair',
                'service_provider' => 'ATL Machine Repair',
                'frequency' => 'Monthly',
                'start_date' => '2026-03-20',
                'next_service_date' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'service_date' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'cost' => 120.00,
            ]);
        }

        $compressorAsset = $createdAssets['ASSET-007'] ?? null;
        if ($compressorAsset) {
            AssetMaintenanceRecord::create([
                'asset_id' => $compressorAsset->id,
                'record_type' => 'schedule',
                'maintenance_type' => 'Emergency Repair',
                'maintenance_title' => 'Pressure Relief Valve Replacement',
                'service_type' => 'Service Due',
                'description' => 'Replace leaking 175 PSI safety relief valve and inspect tank drain.',
                'status' => 'Scheduled',
                'assigned_to' => 'Mecarvi Internal Team',
                'service_provider' => 'Mecarvi Internal Team',
                'frequency' => 'Every 3 Months',
                'start_date' => '2026-03-20',
                'next_service_date' => Carbon::now()->addDays(8)->format('Y-m-d'),
                'service_date' => Carbon::now()->addDays(8)->format('Y-m-d'),
                'cost' => 280.00,
            ]);
        }

        $hvacAsset = $createdAssets['ASSET-010'] ?? null;
        if ($hvacAsset) {
            AssetMaintenanceRecord::create([
                'asset_id' => $hvacAsset->id,
                'record_type' => 'schedule',
                'maintenance_type' => 'Routine Maintenance',
                'maintenance_title' => 'Seasonal Filter & Coil Overhaul',
                'service_type' => 'Filter Replacement',
                'description' => 'Replace MERV 13 air filters and pressure-wash condenser coils.',
                'status' => 'Scheduled',
                'assigned_to' => 'Johnson Electronics',
                'service_provider' => 'Johnson Electronics',
                'frequency' => 'Every 6 Months',
                'start_date' => '2026-04-01',
                'next_service_date' => Carbon::now()->addDays(22)->format('Y-m-d'),
                'service_date' => Carbon::now()->addDays(22)->format('Y-m-d'),
                'cost' => 350.00,
            ]);
        }

        // 5. Seed Activity Logs
        $toolKit = $createdAssets['ASSET-013'] ?? null;
        $printer = $createdAssets['ASSET-004'] ?? null;
        $table = $createdAssets['ASSET-006'] ?? null;
        $compressor = $createdAssets['ASSET-007'] ?? null;

        AssetActivityLog::create([
            'asset_id' => $toolKit ? $toolKit->id : null,
            'action_type' => 'created',
            'title' => 'New asset added',
            'target_name' => 'Tool Kit (ASSET-013)',
            'description' => 'Added new master maintenance toolkit for the Georgia facility.',
            'performed_by' => 'Admin',
            'created_at' => Carbon::now()->subHours(2),
        ]);

        AssetActivityLog::create([
            'asset_id' => $printer ? $printer->id : null,
            'action_type' => 'maintenance_updated',
            'title' => 'Maintenance status updated',
            'target_name' => 'Office Printer (ASSET-004)',
            'description' => 'Status changed to Under Maintenance for roller inspection.',
            'performed_by' => 'Technician',
            'created_at' => Carbon::now()->subHours(5),
        ]);

        AssetActivityLog::create([
            'asset_id' => $table ? $table->id : null,
            'action_type' => 'info_updated',
            'title' => 'Asset information updated',
            'target_name' => 'Cutting Table (ASSET-006)',
            'description' => 'Updated departmental assignment and location records.',
            'performed_by' => 'Staff',
            'created_at' => Carbon::now()->subDays(1),
        ]);

        AssetActivityLog::create([
            'asset_id' => $compressor ? $compressor->id : null,
            'action_type' => 'out_of_service',
            'title' => 'Asset marked out of service',
            'target_name' => 'Air Compressor (ASSET-007)',
            'description' => 'Pressure valve leak detected during routine inspection.',
            'performed_by' => 'Admin',
            'created_at' => Carbon::now()->subDays(2),
        ]);

        // 6. Seed All 12 Asset Settings Categories
        $settingsData = [
            'asset_categories' => [
                ['name' => 'Production Equipment', 'dot_color' => 'blue'],
                ['name' => 'Office Equipment', 'dot_color' => 'blue'],
                ['name' => 'IT Equipment', 'dot_color' => 'red'],
                ['name' => 'Furniture & Fixtures', 'dot_color' => 'green'],
                ['name' => 'Vehicles', 'dot_color' => 'purple'],
                ['name' => 'Packaging Machinery', 'dot_color' => 'cyan'],
                ['name' => 'Printing Equipment', 'dot_color' => 'orange'],
                ['name' => 'Security Systems', 'dot_color' => 'emerald'],
                ['name' => 'Warehouse Tools', 'dot_color' => 'yellow'],
                ['name' => 'Audio / Visual', 'dot_color' => 'blue'],
                ['name' => 'Facility Maintenance', 'dot_color' => 'purple'],
                ['name' => 'Quality Inspection', 'dot_color' => 'red'],
            ],
            'maintenance_types' => [
                ['name' => 'Preventive Maintenance', 'dot_color' => 'blue'],
                ['name' => 'Corrective Maintenance', 'dot_color' => 'green'],
                ['name' => 'Routine Maintenance', 'dot_color' => 'purple'],
                ['name' => 'Inspection', 'dot_color' => 'blue'],
                ['name' => 'Calibration', 'dot_color' => 'orange'],
                ['name' => 'Emergency Repair', 'dot_color' => 'red'],
                ['name' => 'Software Update', 'dot_color' => 'cyan'],
                ['name' => 'Safety Audit', 'dot_color' => 'emerald'],
            ],
            'service_types' => [
                ['name' => 'Routine Service', 'dot_color' => 'blue'],
                ['name' => 'Repair Service', 'dot_color' => 'red'],
                ['name' => 'Installation', 'dot_color' => 'blue'],
                ['name' => 'Inspection Service', 'dot_color' => 'green'],
                ['name' => 'Calibration Service', 'dot_color' => 'orange'],
                ['name' => 'Belt & Gear Overhaul', 'dot_color' => 'purple'],
                ['name' => 'Oil & Lubrication', 'dot_color' => 'cyan'],
                ['name' => 'Electronics Diagnostic', 'dot_color' => 'yellow'],
            ],
            'service_providers' => [
                ['name' => 'Tajima Authorized Service', 'contact_person' => 'Daniel Sato', 'phone' => '+1 718 555-0199', 'dot_color' => 'blue'],
                ['name' => 'ATL Machine Repair', 'contact_person' => 'Kevin White', 'phone' => '+1 404 555-0145', 'dot_color' => 'red'],
                ['name' => 'Mecarvi Internal Team', 'contact_person' => 'Monique Brown', 'phone' => '+1 470 555-0167', 'dot_color' => 'purple'],
                ['name' => 'StitchPro Services', 'contact_person' => 'Jason Lee', 'phone' => '+1 305 555-0123', 'dot_color' => 'green'],
                ['name' => 'Johnson Electronics', 'contact_person' => 'Mark Johnson', 'phone' => '+1 678 555-0188', 'dot_color' => 'yellow'],
                ['name' => 'Brother Technicians', 'contact_person' => 'Alex Vance', 'phone' => '+1 212 555-0144', 'dot_color' => 'cyan'],
                ['name' => 'Ricoma Care Direct', 'contact_person' => 'Sarah Connor', 'phone' => '+1 305 555-0199', 'dot_color' => 'blue'],
            ],
            'document_types' => [
                ['name' => 'Purchase Invoices', 'dot_color' => 'blue'],
                ['name' => 'Warranty Certificates', 'dot_color' => 'green'],
                ['name' => 'User Manuals', 'dot_color' => 'purple'],
                ['name' => 'Maintenance Reports', 'dot_color' => 'orange'],
                ['name' => 'Inspection Checklists', 'dot_color' => 'blue'],
                ['name' => 'Calibration Certificates', 'dot_color' => 'red'],
                ['name' => 'Photos & Diagrams', 'dot_color' => 'cyan'],
            ],
            'locations' => [
                ['name' => 'Brooklyn Main Production Plant', 'address' => "123 Industrial Blvd\nBrooklyn, NY 11207", 'dot_color' => 'blue'],
                ['name' => 'Alpharetta Fulfillment Hub', 'address' => "450 North Point Pkwy\nAlpharetta, GA 30022", 'dot_color' => 'green'],
                ['name' => 'Forest Park Embroidery Shop', 'address' => "820 Central Ave\nForest Park, GA 30297", 'dot_color' => 'red'],
                ['name' => 'McDonough Warehouse', 'address' => "100 Industrial Pkwy\nMcDonough, GA 30253", 'dot_color' => 'purple'],
                ['name' => 'South Fulton Logistics Center', 'address' => "5500 Oakley Industrial Blvd\nSouth Fulton, GA 30213", 'dot_color' => 'cyan'],
                ['name' => 'Douglasville Facility', 'address' => "7000 Douglas Blvd\nDouglasville, GA 30135", 'dot_color' => 'orange'],
            ],
            'brands' => [
                ['name' => 'Tajima', 'dot_color' => 'blue'],
                ['name' => 'Barudan', 'dot_color' => 'green'],
                ['name' => 'Brother', 'dot_color' => 'red'],
                ['name' => 'Ricoma', 'dot_color' => 'purple'],
                ['name' => 'Melco', 'dot_color' => 'orange'],
                ['name' => 'HappyJapan', 'dot_color' => 'cyan'],
                ['name' => 'Dell', 'dot_color' => 'blue'],
                ['name' => 'HP', 'dot_color' => 'green'],
                ['name' => 'APC', 'dot_color' => 'yellow'],
                ['name' => 'Herman Miller', 'dot_color' => 'purple'],
                ['name' => 'Global Industrial', 'dot_color' => 'emerald'],
                ['name' => 'DeWalt', 'dot_color' => 'yellow'],
                ['name' => 'Ingersoll Rand', 'dot_color' => 'red'],
                ['name' => 'Crown', 'dot_color' => 'orange'],
            ],
            'departments' => [
                ['name' => 'Production', 'dot_color' => 'blue'],
                ['name' => 'IT & Design', 'dot_color' => 'green'],
                ['name' => 'Administration', 'dot_color' => 'purple'],
                ['name' => 'Maintenance', 'dot_color' => 'red'],
                ['name' => 'Warehouse & Logistics', 'dot_color' => 'orange'],
                ['name' => 'Shipping & Packaging', 'dot_color' => 'cyan'],
                ['name' => 'Quality Control', 'dot_color' => 'emerald'],
            ],
            'assigned_to' => [
                ['name' => 'Production Team', 'email' => 'production@mecarvi.com', 'dot_color' => 'blue'],
                ['name' => 'Design Team', 'email' => 'design@mecarvi.com', 'dot_color' => 'green'],
                ['name' => 'Lead Digitizer', 'email' => 'digitizing@mecarvi.com', 'dot_color' => 'purple'],
                ['name' => 'Office Staff', 'email' => 'office@mecarvi.com', 'dot_color' => 'red'],
                ['name' => 'Facilities Team', 'email' => 'facilities@mecarvi.com', 'dot_color' => 'orange'],
                ['name' => 'IT Infrastructure Team', 'email' => 'it@mecarvi.com', 'dot_color' => 'cyan'],
                ['name' => 'Warehouse Lead', 'email' => 'warehouse@mecarvi.com', 'dot_color' => 'yellow'],
                ['name' => 'Shipping Team', 'email' => 'shipping@mecarvi.com', 'dot_color' => 'emerald'],
            ],
            'asset_statuses' => [
                ['name' => 'In Use', 'dot_color' => 'green'],
                ['name' => 'Under Maintenance', 'dot_color' => 'orange'],
                ['name' => 'Out of Service', 'dot_color' => 'red'],
                ['name' => 'In Storage', 'dot_color' => 'blue'],
                ['name' => 'Disposed', 'dot_color' => 'purple'],
            ],
            'conditions' => [
                ['name' => 'Brand New', 'dot_color' => 'blue'],
                ['name' => 'Like New', 'dot_color' => 'green'],
                ['name' => 'Good', 'dot_color' => 'cyan'],
                ['name' => 'Fair', 'dot_color' => 'yellow'],
                ['name' => 'Poor', 'dot_color' => 'orange'],
                ['name' => 'Needs Replacement', 'dot_color' => 'red'],
            ],
            'purchase_types' => [
                ['name' => 'Purchased', 'dot_color' => 'blue'],
                ['name' => 'Leased', 'dot_color' => 'green'],
                ['name' => 'Rented', 'dot_color' => 'purple'],
                ['name' => 'Financed', 'dot_color' => 'orange'],
                ['name' => 'Donated / Transferred', 'dot_color' => 'cyan'],
            ],
        ];

        foreach ($settingsData as $categoryType => $items) {
            foreach ($items as $idx => $item) {
                AssetSetting::create([
                    'category_type' => $categoryType,
                    'name' => $item['name'],
                    'dot_color' => $item['dot_color'] ?? 'blue',
                    'contact_person' => $item['contact_person'] ?? null,
                    'phone' => $item['phone'] ?? null,
                    'email' => $item['email'] ?? null,
                    'address' => $item['address'] ?? null,
                    'sort_order' => $idx + 1,
                ]);
            }
        }
    }
}
