<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserPanelBanner extends Model
{
    use HasFactory;

    protected $table = 'user_panel_banners';

    protected $fillable = [
        'page_key',
        'title',
        'subtitle',
        'description',
        'footer_text',
        'badge_text',
        'badge_subtext',
        'button_text',
        'button_url',
        'image_path',
        'preset_image_url',
        'theme_color',
        'accent_color',
        'is_active',
    ];

    protected $casts = [
        'is_active' => 'boolean',
    ];

    protected $appends = [
        'image_url',
    ];

    /**
     * Get the full URL for the banner image.
     */
    public function getImageUrlAttribute(): string
    {
        if (!empty($this->image_path)) {
            if (str_starts_with($this->image_path, 'http://') || str_starts_with($this->image_path, 'https://')) {
                return $this->image_path;
            }
            return '/storage/' . ltrim($this->image_path, '/');
        }

        if (!empty($this->preset_image_url)) {
            return $this->preset_image_url;
        }

        $defaults = self::getDefaultsForPage($this->page_key);
        return $defaults['image_url'] ?? '/assets/images/orders_banner_hd.jpg';
    }

    /**
     * Default configurations for every user panel page.
     */
    public static function getDefaults(): array
    {
        return [
            'orders' => [
                'page_key' => 'orders',
                'page_name' => 'Orders',
                'category' => 'Orders & Proofs',
                'title' => 'Your Orders',
                'subtitle' => 'Custom Creations On Their Way!',
                'description' => 'Track, manage and view all your orders.',
                'footer_text' => 'Thank you for choosing Mecarvi Embroidery!',
                'badge_text' => 'STITCHING IDEAS INTO REALITY',
                'badge_subtext' => 'Apparel, Branded Gear & More...',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/orders_banner_hd.jpg',
                'theme_color' => '#059669',
                'accent_color' => '#10b981',
                'is_active' => true,
            ],
            'quotations' => [
                'page_key' => 'quotations',
                'page_name' => 'Quotations',
                'category' => 'Orders & Proofs',
                'title' => 'Your Quotations',
                'subtitle' => 'Tailored Pricing for Your Custom Projects',
                'description' => 'Review quotes, approve estimates, and convert custom quotes into active orders.',
                'footer_text' => 'Fast Turnaround & Transparent Pricing',
                'badge_text' => 'CUSTOM EMBROIDERY QUOTES',
                'badge_subtext' => 'Instant Digital Proofs Included',
                'button_text' => 'Request New Quote',
                'button_url' => '/dashboard/quotations',
                'image_url' => '/assets/images/admin_quotes_banner.jpg',
                'theme_color' => '#2563eb',
                'accent_color' => '#3b82f6',
                'is_active' => true,
            ],
            'order_proofs' => [
                'page_key' => 'order_proofs',
                'page_name' => 'Order Proofs',
                'category' => 'Orders & Proofs',
                'title' => 'Order Proof Approvals',
                'subtitle' => 'Inspect & Approve Your Embroidery Artwork',
                'description' => 'View stitch mockups, check color accuracy, and approve proofs for production.',
                'footer_text' => '100% Satisfaction Guarantee on Every Stitch',
                'badge_text' => 'PRECISION EMBROIDERY DIGITIZING',
                'badge_subtext' => 'Review Every Thread & Stitch Detail',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_order_banner.jpg',
                'theme_color' => '#7c3aed',
                'accent_color' => '#8b5cf6',
                'is_active' => true,
            ],
            'order_verifications' => [
                'page_key' => 'order_verifications',
                'page_name' => 'Order Verifications',
                'category' => 'Orders & Proofs',
                'title' => 'Order Verification Center',
                'subtitle' => 'Secure Verification for Large Orders',
                'description' => 'Some orders require additional verification. Upload documents to ensure rapid processing.',
                'footer_text' => 'Bank-Grade Security & Privacy Protection',
                'badge_text' => 'VERIFIED TRANSACTIONS',
                'badge_subtext' => 'Encrypted & Safe Account Protection',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/order-verification/banner_art.png',
                'theme_color' => '#4f46e5',
                'accent_color' => '#6366f1',
                'is_active' => true,
            ],
            'track_orders' => [
                'page_key' => 'track_orders',
                'page_name' => 'Track Orders',
                'category' => 'Orders & Proofs',
                'title' => 'Live Order Tracking',
                'subtitle' => 'Real-Time Updates From Production to Delivery',
                'description' => 'Follow your parcels journey with carrier tracking and instant shipment updates.',
                'footer_text' => 'Fast Nationwide & International Shipping',
                'badge_text' => 'EXPRESS DISPATCH',
                'badge_subtext' => 'Real-Time Carrier GPS Tracking',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_order_banner_hd.jpg',
                'theme_color' => '#0284c7',
                'accent_color' => '#0ea5e9',
                'is_active' => true,
            ],
            'order_returns' => [
                'page_key' => 'order_returns',
                'page_name' => 'Order Returns',
                'category' => 'Orders & Proofs',
                'title' => 'Returns & Replacements',
                'subtitle' => 'Hassle-Free Return Requests',
                'description' => 'Need help with an item? Submit return or replacement requests effortlessly.',
                'footer_text' => 'We Stand Behind Every Piece We Produce',
                'badge_text' => '30-DAY SATISFACTION GUARANTEE',
                'badge_subtext' => 'Dedicated Customer Resolution Team',
                'button_text' => 'Start A Return',
                'button_url' => '/order-returns',
                'image_url' => '/assets/images/returns/banner-woman-box.jpg',
                'theme_color' => '#db2777',
                'accent_color' => '#ec4899',
                'is_active' => true,
            ],
            'customer_refunds' => [
                'page_key' => 'customer_refunds',
                'page_name' => 'Customer Refunds',
                'category' => 'Financial & Digital',
                'title' => 'Refund Status & History',
                'subtitle' => 'Transparent Refund Processing',
                'description' => 'Track approved refund amounts, store credit adjustments, and payout timelines.',
                'footer_text' => 'Direct to Original Payment Method or Wallet',
                'badge_text' => 'SECURE REFUND DISBURSEMENT',
                'badge_subtext' => 'Immediate Wallet Credits Available',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_order_banner.jpg',
                'theme_color' => '#d97706',
                'accent_color' => '#f59e0b',
                'is_active' => true,
            ],
            'downloads' => [
                'page_key' => 'downloads',
                'page_name' => 'Downloads',
                'category' => 'Financial & Digital',
                'title' => 'Digital Embroidery Files',
                'subtitle' => 'DST, PES, EMB & Vector Assets',
                'description' => 'Access and download all your digitizing files, artwork proofs, and invoices anytime.',
                'footer_text' => 'Permanent Cloud Storage on All Digitized Files',
                'badge_text' => 'INSTANT DIGITAL ASSETS',
                'badge_subtext' => 'Multi-Format Machine Compatibility',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_quotes_banner.jpg',
                'theme_color' => '#0d9488',
                'accent_color' => '#14b8a6',
                'is_active' => true,
            ],
            'wallet' => [
                'page_key' => 'wallet',
                'page_name' => 'Wallet',
                'category' => 'Financial & Digital',
                'title' => 'Mecarvi Wallet & Credits',
                'subtitle' => 'Seamless Store Credits & Instant Checkout',
                'description' => 'Top up balance, redeem promotional credits, and manage wallet transactions.',
                'footer_text' => 'Get 5% Extra Bonus on Wallet Recharges Over $100',
                'badge_text' => 'INSTANT STORE CREDIT',
                'badge_subtext' => 'Zero Transaction Fees on Wallet Pay',
                'button_text' => 'Add Funds',
                'button_url' => '/wallet',
                'image_url' => '/assets/images/admin_order_banner_hd.jpg',
                'theme_color' => '#16a34a',
                'accent_color' => '#22c55e',
                'is_active' => true,
            ],
            'memberships' => [
                'page_key' => 'memberships',
                'page_name' => 'Membership',
                'category' => 'Benefits & Rewards',
                'title' => 'VIP Member Privileges',
                'subtitle' => 'Unlock Exclusive Wholesale Rates & Priority Production',
                'description' => 'Enjoy free digitizing, accelerated turnarounds, and dedicated embroidery specialists.',
                'footer_text' => 'Upgrade or Manage Your VIP Membership Tier Anytime',
                'badge_text' => 'VIP ADVANTAGE CLUB',
                'badge_subtext' => 'Up to 25% Off Every Single Order',
                'button_text' => 'View Tiers',
                'button_url' => '/memberships',
                'image_url' => '/assets/images/admin_quotes_banner.jpg',
                'theme_color' => '#9333ea',
                'accent_color' => '#a855f7',
                'is_active' => true,
            ],
            'gift_cards' => [
                'page_key' => 'gift_cards',
                'page_name' => 'Gift Cards',
                'category' => 'Benefits & Rewards',
                'title' => 'Mecarvi Digital Gift Cards',
                'subtitle' => 'The Perfect Gift for Crafters & Businesses',
                'description' => 'Send custom gift cards instantly to friends, colleagues, or teams with personalized notes.',
                'footer_text' => 'Gift Cards Never Expire & Have No Hidden Fees',
                'badge_text' => 'INSTANT DIGITAL DELIVERY',
                'badge_subtext' => 'Redeemable on All Products & Services',
                'button_text' => 'Purchase Gift Card',
                'button_url' => '/gift-cards',
                'image_url' => '/images/packaging/banner_box.png',
                'theme_color' => '#ea580c',
                'accent_color' => '#f97316',
                'is_active' => true,
            ],
            'loyalty_rewards' => [
                'page_key' => 'loyalty_rewards',
                'page_name' => 'Loyalty Rewards',
                'category' => 'Benefits & Rewards',
                'title' => 'Stitch Rewards Program',
                'subtitle' => 'Earn Points on Every Dollar Spent',
                'description' => 'Redeem accumulated reward points for instant checkout discounts and free apparel.',
                'footer_text' => 'Points Never Expire While Your Account Remains Active',
                'badge_text' => 'EARN & REDEEM POINTS',
                'badge_subtext' => 'Tier Multipliers & Birthday Bonus Points',
                'button_text' => 'Redeem Points',
                'button_url' => '/loyalty-rewards',
                'image_url' => '/assets/images/admin_order_banner.jpg',
                'theme_color' => '#ca8a04',
                'accent_color' => '#eab308',
                'is_active' => true,
            ],
            'coupons' => [
                'page_key' => 'coupons',
                'page_name' => 'Coupons & Deals',
                'category' => 'Benefits & Rewards',
                'title' => 'Coupons & Exclusive Deals',
                'subtitle' => 'Save Big on Your Next Custom Order',
                'description' => 'Browse seasonal promo codes, flash discounts, and bulk embroidery promotions.',
                'footer_text' => 'Automatic Best Coupon Applied at Checkout',
                'badge_text' => 'VERIFIED DISCOUNTS',
                'badge_subtext' => 'Stackable Savings on Select Collections',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/images/deals/polo_bundle_banner.png',
                'theme_color' => '#e11d48',
                'accent_color' => '#f43f5e',
                'is_active' => true,
            ],
            'affiliate' => [
                'page_key' => 'affiliate',
                'page_name' => 'Affiliate Referral',
                'category' => 'Benefits & Rewards',
                'title' => 'Affiliate Partner Hub',
                'subtitle' => 'Earn Generous Recurring Commissions',
                'description' => 'Share your custom referral link and earn commissions on every client you introduce.',
                'footer_text' => 'Monthly Automated Payouts via PayPal or Bank Wire',
                'badge_text' => 'PARTNER PROGRAM',
                'badge_subtext' => '10% Commission on Referred Purchases',
                'button_text' => 'Copy Referral Link',
                'button_url' => '/affiliate-information',
                'image_url' => '/assets/images/admin_order_banner_hd.jpg',
                'theme_color' => '#4f46e5',
                'accent_color' => '#6366f1',
                'is_active' => true,
            ],
            'wishlist' => [
                'page_key' => 'wishlist',
                'page_name' => 'Wishlist',
                'category' => 'Product & Activity',
                'title' => 'Your Saved Wishlist',
                'subtitle' => 'Keep Track of Favorite Apparel & Custom Styles',
                'description' => 'Save favorite items for later, organize collections, and move them to cart with one click.',
                'footer_text' => 'We Notify You When Wishlist Items Go on Sale',
                'badge_text' => 'CURATED SELECTIONS',
                'badge_subtext' => 'Share Your Wishlist With Your Team',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_order_banner.jpg',
                'theme_color' => '#ec4899',
                'accent_color' => '#f472b6',
                'is_active' => true,
            ],
            'reviews' => [
                'page_key' => 'reviews',
                'page_name' => 'Product Reviews',
                'category' => 'Product & Activity',
                'title' => 'Your Product Reviews',
                'subtitle' => 'Share Your Feedback & Earn Loyalty Points',
                'description' => 'View all your submitted product reviews and ratings. Help other customers choose.',
                'footer_text' => 'Earn 50 Reward Points for Every Verified Review',
                'badge_text' => 'VERIFIED BUYER REVIEWS',
                'badge_subtext' => 'Honest Feedback Shapes Our Products',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/wishlist/rollup-banner.svg',
                'theme_color' => '#f59e0b',
                'accent_color' => '#fbbf24',
                'is_active' => true,
            ],
            'product_questions' => [
                'page_key' => 'product_questions',
                'page_name' => 'Product Questions',
                'category' => 'Product & Activity',
                'title' => 'Product Q&A Center',
                'subtitle' => 'Expert Answers to Your Inquiries',
                'description' => 'Check answers from our digitizing masters and product specialists regarding sizing and materials.',
                'footer_text' => 'Average Response Time Under 2 Hours',
                'badge_text' => 'TECHNICAL EXPERTISE',
                'badge_subtext' => 'Embroidery & Digitizing Specialists On Standby',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_quotes_banner.jpg',
                'theme_color' => '#0284c7',
                'accent_color' => '#38bdf8',
                'is_active' => true,
            ],
            'reported_products' => [
                'page_key' => 'reported_products',
                'page_name' => 'Reported Products',
                'category' => 'Product & Activity',
                'title' => 'Quality & Content Inquiries',
                'subtitle' => 'Ensuring Integrity & Superior Craftsmanship',
                'description' => 'Track reported issues or concerns regarding product descriptions or specifications.',
                'footer_text' => 'Committed to Accurate and High-Quality Listings',
                'badge_text' => 'QUALITY ASSURANCE',
                'badge_subtext' => 'Dedicated Compliance Review',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_order_banner.jpg',
                'theme_color' => '#64748b',
                'accent_color' => '#94a3b8',
                'is_active' => true,
            ],
            'messages' => [
                'page_key' => 'messages',
                'page_name' => 'Messages',
                'category' => 'Support & Disputes',
                'title' => 'Direct Messenger',
                'subtitle' => 'Connect Directly With Your Dedicated Project Manager',
                'description' => 'Send files, discuss thread colors, and chat in real-time about your production orders.',
                'footer_text' => 'Live Chat Support Available Monday - Saturday',
                'badge_text' => 'PRIORITY MESSAGING',
                'badge_subtext' => 'Fast Direct Communication',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/admin_order_banner_hd.jpg',
                'theme_color' => '#2563eb',
                'accent_color' => '#60a5fa',
                'is_active' => true,
            ],
            'support_tickets' => [
                'page_key' => 'support_tickets',
                'page_name' => 'Support Tickets',
                'category' => 'Support & Disputes',
                'title' => 'Helpdesk & Support Tickets',
                'subtitle' => 'Dedicated Assistance for Any Inquiries',
                'description' => 'Create support tickets, track ticket status, and receive expert assistance from our team.',
                'footer_text' => '24/7 Dedicated Client Support',
                'badge_text' => 'CUSTOMER FIRST DESK',
                'badge_subtext' => 'Resolved With Care & Attention',
                'button_text' => 'Create New Ticket',
                'button_url' => '/support-tickets',
                'image_url' => '/assets/images/admin_quotes_banner.jpg',
                'theme_color' => '#059669',
                'accent_color' => '#34d399',
                'is_active' => true,
            ],
            'disputes' => [
                'page_key' => 'disputes',
                'page_name' => 'Dispute Center',
                'category' => 'Support & Disputes',
                'title' => 'Resolution & Dispute Center',
                'subtitle' => 'Fair and Transparent Case Mediation',
                'description' => 'Manage active disputes, upload supporting evidence, and track mediation progress.',
                'footer_text' => 'Neutral Case Review by Senior Quality Managers',
                'badge_text' => 'BUYER PROTECTION',
                'badge_subtext' => 'Escalated Mediation Protocol',
                'button_text' => '',
                'button_url' => '',
                'image_url' => '/assets/images/disputes/dispute-banner-showcase.jpg',
                'theme_color' => '#e11d48',
                'accent_color' => '#f43f5e',
                'is_active' => true,
            ],
            'dashboard' => [
                'page_key' => 'dashboard',
                'page_name' => 'Account Dashboard',
                'category' => 'Account & Overview',
                'title' => 'Welcome to Your Mecarvi Portal',
                'subtitle' => 'Your Headquarters for Custom Embroidery',
                'description' => 'Manage orders, download digitizing proofs, monitor wallet balance, and track shipments.',
                'footer_text' => 'Thank you for being a valued Mecarvi partner!',
                'badge_text' => 'MECARVI EMBROIDERY HUB',
                'badge_subtext' => 'Precision Digitizing & Apparel',
                'button_text' => 'Explore Products',
                'button_url' => '/products',
                'image_url' => '/assets/images/orders_banner_hd.jpg',
                'theme_color' => '#059669',
                'accent_color' => '#10b981',
                'is_active' => true,
            ],
        ];
    }

    /**
     * Get default settings for a specific page.
     */
    public static function getDefaultsForPage(string $pageKey): array
    {
        $all = self::getDefaults();
        return $all[$pageKey] ?? [
            'page_key' => $pageKey,
            'page_name' => ucfirst(str_replace('_', ' ', $pageKey)),
            'category' => 'General',
            'title' => ucfirst(str_replace('_', ' ', $pageKey)),
            'subtitle' => 'Mecarvi Custom Embroidery',
            'description' => 'Manage your activities on Mecarvi.',
            'footer_text' => 'Thank you for choosing Mecarvi Embroidery!',
            'badge_text' => 'STITCHING IDEAS INTO REALITY',
            'badge_subtext' => 'Apparel, Branded Gear & More...',
            'button_text' => '',
            'button_url' => '',
            'image_url' => '/assets/images/orders_banner_hd.jpg',
            'theme_color' => '#059669',
            'accent_color' => '#10b981',
            'is_active' => true,
        ];
    }
}
